import turtle
turtle.setup(300,300)
turtle.penup()
turtle.fd(0)
turtle.pendown()
turtle.pensize(50)
turtle.color("yellow")
turtle.circle(15,360)

turtle.goto(10,17)
turtle.penup()
turtle.fd(0)
turtle.pendown()
turtle.pensize(5)
turtle.color("black")
turtle.circle(5,360)
turtle.penup()

turtle.goto(-10,17)
turtle.penup()
turtle.fd(0)
turtle.pendown()
turtle.pensize(5)
turtle.color("black")
turtle.circle(5,360)
turtle.penup()

turtle.goto(0,9)
turtle.penup()
turtle.fd(0)
turtle.pendown()
turtle.pensize(5)
turtle.color("black")
turtle.right(90)
turtle.fd(10)
turtle.penup()

turtle.goto(-14,-5)
turtle.penup()
turtle.fd(0)
turtle.pendown()
turtle.pensize(5)
turtle.color("red")
turtle.left(45)
turtle.fd(10)
turtle.left(45)
turtle.fd(15)
turtle.left(45)
turtle.fd(10)
turtle.penup()

turtle.done()
